"""empty message

Revision ID: 92feb2243079
Revises: 6ca2cb4590ba
Create Date: 2021-11-22 21:16:56.333441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92feb2243079'
down_revision = '6ca2cb4590ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    # ### end Alembic commands ###
